#
# Valid configuration
#----------------------------------
#target = "riscv32imac-esp-espidf"
#MCU="esp32c6"
#----------------------------------
#
#
#target = "riscv32imac-esp-espidf"
#MCU="esp32c6"
#----------------------------------
#
#MCU="esp32s3"
#target = "xtensa-esp32s3-espidf"
#----------------------------------

[build]
target = "xtensa-esp32s3-espidf"
#target = "riscv32imac-esp-espidf"
#target = "riscv32imc-esp-espidf"

[env]
#MCU="esp32c3"
#MCU="esp32c6"
MCU="esp32s3"
# 1. Force the exact ESP-IDF version
ESP_IDF_VERSION = "v5.4"

# __________________________
# This is used by esp32c3
# __________________________
[target.riscv32imc-esp-espidf]
#linker = "ldproxy"
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = [ "--cfg",  "espidf_time64","-C","default-linker-libraries"]
# This is used by esp32c6
# __________________________
[target.riscv32imac-esp-espidf]
linker = "ldproxy"
#linker = "riscv32-esp-elf-gcc"
# Add this line to tell ldproxy exactly which C compiler to wrap
#rustflags = ["-C", "linker=riscv32-esp-elf-gcc"]
runner = "espflash flash --monitor"
rustflags = [ "--cfg",  "espidf_time64",
        "-C","default-linker-libraries",
        "-C","link-arg=-lgcc",
]

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = [ "--cfg",  "espidf_time64","-C","default-linker-libraries"]

[unstable]
build-std = ["std", "panic_abort"]

# Note: this variable is not used by the pio builder (`cargo build --features pio`)
#ESP_IDF_VERSION = "v5.3.3"

